version: '3'
services:

  bench:
    image: williamyeh/wrk:4.0.2
    entrypoint: >
        sh -c "wrk -t12 -c400 -d5s http://flask:5000
        && wrk -t12 -c400 -d5s http://gunicorn:8080
        && wrk -t12 -c400 -d5s http://express:8080
        && wrk -t12 -c400 -d5s http://spring-boot:8080/hello/world
        && wrk -t12 -c400 -d5s http://lumen
        && wrk -t12 -c400 -d5s http://sinatra:5000
        && wrk -t12 -c400 -d5s http://scotty:3000
        && wrk -t12 -c400 -d5s http://servant:8081
        && wrk -t12 -c400 -d5s http://revel:9000
        && wrk -t12 -c400 -d5s http://silex/hello/world
        && wrk -t12 -c400 -d5s http://koa:8080"
    depends_on:
      - flask
      - express
      - gunicorn
      - spring-boot
      - koa
      - lumen
      - sinatra
      - scotty
      - silex
      - servant
      - revel
    links:
      - flask
      - express
      - gunicorn
      - spring-boot
      - koa
      - lumen
      - sinatra
      - scotty
      - silex
      - servant
      - revel

  flask:
    image: "tullyrankin/flask-hello-world"
    logging:
      driver: "none"

  gunicorn:
    image: "macinv/gunicorn-example"
    logging:
      driver: "none"

  express:
    image: "kornkitti/express-hello-world"
    logging:
      driver: "none"

  spring-boot:
    image: "saturnism/spring-boot-helloworld-service"
    logging:
      driver: "none"

  lumen:
    image: "tonypai/docker-lumen"
    logging:
      driver: "none"

  sinatra:
    image: "luisbebop/docker-sinatra-hello-world"
    logging:
      driver: "none"

  scotty:
    image: "grdvnl/helloscotty"
    logging:
      driver: "none"

  servant:
    image: "fosskers/servant-docker:1.0"
    logging:
      driver: "none"

  silex:
    image: "sskorc/silex"
    logging:
      driver: "none"

  revel:
    image: "shokwon/go-revel"
    logging:
      driver: "none"

  # rails:
  # image: "sqmk/dind-docker-compose"
  #   entrypoint: sh -c "apk update && apk add git && git clone https://github.com/mookjp/rails-docker-example.git && cd rails-docker-example && docker-compose up"
  #     - "80:80"
  #   volumes:
  #       - /var/run/docker.sock:/var/run/docker.sock

  koa:
    image: "mbukosky/koa-hello"
    logging:
      driver: "none"
